sketch_sets = {}
debug_level = 2
x_clr = 'k'
y_clr = 'k'
x_lbl = 'X'
y_lbl = 'Y'
model_precision = 0.01
gui_title = "Title"
upper_x_bound = 100
upper_y_bound = 100
lower_x_bound = 0
lower_y_bound = 0
points_to_gen = 25
randomizer = None
main_graph_title = 'Main Graph'